=== Z-Y00/rocm-systems/emulation/plugin/schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Emulator Plugin Manifest",
	"type": "object",
	"required": ["abi_version", "name", "version"],
	"properties": {
		"abi_version": {
			"type": "integer",
			"minimum": 1
		},
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"version": {
			"type": "string"
		},
		"contact": {
			"type": "string"
		},
		"arguments": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"description": {
						"type": "string"
					},
					"type": {
						"type": "string"
					},
					"default": true
				},
				"additionalProperties": true
			}
		}
	},
	"additionalProperties": true
}

=== Z-Y00/rocm-systems/emulation/rocjitsu/plugin/example/instruction_counter.json
{
    "abi_version": 1,
    "name": "instruction_counter",
    "description": "Counts the number of instructions executed.",
    "version": "0.1.0",
    "contact": "Ada Rosa <Ada.Rosa@amd.com>",
    "arguments": {
        "instructions": {
            "description": "A regex used to determine which instructions to count.",
            "type": "string",
            "default": "^.*$"
        }
    }
}
